on: push

jobs:
  ipxe:
    name: Build ${{ matrix.arch }}-${{ matrix.platform }}${{ matrix.sb }}/${{ matrix.driver }}.${{ matrix.extension }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See https://ipxe.org/appnote/buildtargets
        arch: [ i386, x86_64, arm32, arm64 ]
        platform: [ pcbios, efi ]
        sb: [ "", -sb ]
        driver: [ ipxe, undionly, snponly ]
        extension: [ pxe, kpxe, efi ]
        exclude:
          # pcbios platform is not supported on arm
          - arch: arm64
            platform: pcbios
          - arch: arm32
            platform: pcbios
          # pcbios has no secure boot
          - platform: pcbios
            sb: -sb
          # undionly and snponly only work on pcbios and efi respectively
          - driver: undionly
            platform: efi
          - driver: snponly
            platform: pcbios
          # Each extension is only valid on either pcbios or efi
          - platform: pcbios
            extension: efi
          - platform: efi
            extension: pxe
          - platform: efi
            extension: kpxe
        include:
          # Add Ubuntu Cross-Compilation Toolchains based on architecture
          - arch: arm32
            toolchain: gcc-arm-linux-gnueabihf
          - arch: arm64
            toolchain: gcc-aarch64-linux-gnu
          - arch: i386
            toolchain: x86_64-linux-gnux32
          - arch: x86_64
            toolchain: x86_64-linux-gnu
    env:
      TARGET: ${{ matrix.arch }}-${{ matrix.platform }}${{ matrix.sb }}/${{ matrix.driver }}.${{ matrix.extension }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Toolchain
        run: sudo apt-get install --yes "$PACKAGE"
        env:
          PACKAGE: gcc-${{ matrix.toolchain }}
      - name: Build Target
        working-directory: ./ipxe/src
        run: make "bin-$TARGET"
        env:
          CROSS: ${{ matrix.toolchain }}-
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TARGET }}
          path: ipxe/src/bin-${{ env.TARGET }}
          retention-days: 1
